### PR TITLE
Add GitHub automation to release the provider as a package image

### PR DESCRIPTION
**Pull request by ccremer**
## Summary

* This PR introduces automation (`make package-{provider.push}`) to build and push the provider as a package in the Crossplane's package format (see https://crossplane.io/docs/v1.9/reference/xpkg.html#overview)
* To that end, 2 new image streams will be created, 1 deprecated:
`ghcr.io/vshn/provider-cloudscale:<tag>` renamed to `ghcr.io/vshn/provider-cloudscale/controller:<tag>` (existing images will not be moved unless necessary)
`ghcr.io/vshn/provider-cloudscale/package:<tag>` will be the location where the package image (containing the package.yaml file). The tag will be the same as the controller image.

### For Code changes

- [x] Categorize the PR by setting a good title and adding one of the labels:
  `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
  as they show up in the changelog
- [x] PR contains the label `area:operator`
- [x] Link this PR to related issues
- [x] I have not made _any_ changes in the `charts/` directory.

### CODE REVIEW

**Comment by ccremer** [comment]
PR currently is based on #20 , but can be rebased from master after merging to keep the diff manageable

**Comment by ZuGao** [comment]
I tried to install the package via the latest `kubectl-crossplane ` binary and I'm getting an error:
```kubectl crossplane: error: cannot create provider: kubectl-crossplane plugin v1.9.0 might be out of date: the server could not find the requested resource (post providers.pkg.crossplane.io)
```

**Comment by ccremer** [comment]
> 

Well, that's because the image `ghcr.io/vshn/provider-cloudscale/package:latest` hasn't been pushed yet... It should be available after tagging a new release.
Right now you can't install it as a provider, I'm working on a separate PR to install it locally.

**Comment by ZuGao** [comment]
I pushed the latest version but nevertheless it does not work. If you say the installation will happen in a new PR than this LGTM

**Review by ZuGao — APPROVED** [review]

**Comment by ccremer** [comment]
> I pushed the latest version but nevertheless it does not work.

What did you push where?

**Comment by ZuGao** [comment]
> ghcr.io/vshn/provider-cloudscale/package:latest

I ran `make package-push` though I haven't installed crossplane in the cluster. I will try again

**Comment by ccremer** [comment]
> 

Don't waste your time there. You also need to install a docker registry in kind... which I'm engineering right now.

**Pull request merged**
